project/api/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from .views import PhysicalList, PhysicalDetail, UserPhysical, FilterPhysical
from .views import VitalSignsList, VitalSignsDetail, UserVitalSigns, VitalSignsGetAll
from .views import HospitalRecordList, HospitalRecordDetail, UserHospitalRecord, FilterUserHospitalRecord, FilterAllHospitalRecord, HospitalRecordGetAll
from .views import ReExaminationList, ReExaminationDetail
from .views import MedicalList, MedicalDetail, FilterAllMedical
from .views import MedicalDetailGet, MedicalDetailPost, MedicalDetailDetail
from rest_framework_swagger.views import get_swagger_view
schema_view = get_swagger_view(title='My API document')

urlpatterns = (
    url(r'^doc/', schema_view, name='swagger'),
    # #url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
    #url(r'find$', PhysicalFilter.as_view(), name='physical'),

    url(r'physical/$', PhysicalList.as_view(), name='physical'),
    url(r'physical/(?P<pk>[0-9]+)/$', PhysicalDetail.as_view(), name='physical_detail'),
    url(r'physical/user/(?P<pk>[0-9]+)/$', UserPhysical.as_view(), name='user_physical'),
    url(r'physical/filter/(?P<pk>[0-9]+)/$', FilterPhysical.as_view(), name='physical-filter'),

    url(r'vital-signs/$', VitalSignsGetAll.as_view(), name='vital_signs'),
    url(r'vital-signs/(?P<pk>[0-9]+)/$', VitalSignsDetail.as_view(), name='vital_signs_detail'),
    url(r'vital-signs/user/(?P<pk>[0-9]+)/$', UserVitalSigns.as_view(), name='user_vital_signs'),
    
    url(r'hospital-record/$', HospitalRecordGetAll.as_view(), name='hospital_record'),
    url(r'hospital-record/(?P<pk>[0-9]+)/$', HospitalRecordDetail.as_view(), name='hospital_record_detail'),
    url(r'hospital-record/user/(?P<pk>[0-9]+)/$', UserHospitalRecord.as_view(), name="user_hospital_record"),
    url(r'hospital-record/filter/$', FilterAllHospitalRecord.as_view(), name="hospital_record_filter_all"),
    url(r'hospital-record/filter/(?P<pk>[0-9]+)/$', FilterUserHospitalRecord.as_view(), name="hospital_record_filter_user"),
    

    url(r're-examination/hospital_record/(?P<hospital_record_id>[0-9]+)/$', ReExaminationList.as_view(), name='re_examination'),
    url(r're-examination/(?P<pk>[0-9]+)/$', ReExaminationDetail.as_view(), name='re_examination_detail'),

    url(r'medical/$', MedicalList.as_view(), name='medical'),
    url(r'medical/(?P<pk>[0-9]+)/$', MedicalDetail.as_view(), name='medical_detail'),
    url(r'medical/filter$', FilterAllMedical.as_view(), name='medical_filter'),
    #url(r'medical-detail/re-examination/$', MedicalDetailList.as_view(), name='medical_detail_by_re_examination'),
    #url(r'medical-detail/re-examination/(?P<re_examination_id>[0-9]+)/$', MedicalDetailList.as_view(), name='medical_detail_by_re_examination'),
    url(r'medical-detail/get/(?P<re_examination_id>[0-9]+)/$', MedicalDetailGet.as_view(), name='medical_detail_get'),
    url(r'medical-detail/post/(?P<re_examination_id>[0-9]+)/$', MedicalDetailPost.as_view(), name='medical_detail_post'),
    url(r'medical-detail/get/(?P<re_examination_id>[0-9]+)/(?P<pk>[0-9]+)/$', MedicalDetailDetail.as_view(), name='medical_detail_post'),
)
urlpatterns = format_suffix_patterns(urlpatterns)

project/project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required

from api import urls as urls_api
from user import urls as urls_user
from physical import urls as urls_physical
from vital_signs import urls as urls_vital_signs
from hospital_record import urls as urls_hospital_record
from medical import urls as urls_medical
from re_examination import urls as urls_re_examination
# from predict import urls as urls_predict
from django.contrib.auth import views as auth_views

from user.views import Home, register, profile
from predict.views import save_symptom

urlpatterns = [
    path('toppage/', save_symptom, name='index'),
    path('home/', login_required(Home.as_view()), name='home'),
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('profile/', profile, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),

    path('admin/', admin.site.urls),
    # path('home/', include(urls_user)),
    path('api/', include(urls_api)),
    path('physical/', include(urls_physical)),
    path('vital-signs/', include(urls_vital_signs)),
    path('hospital-record/', include(urls_hospital_record)),
    path('medical/', include(urls_medical)),
    path('re-examination/', include(urls_re_examination)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/re_examination/urls.py
from django.urls import path
from . import views
from .views import GetReExaminationList, save_re_examination, GetReExaminationDetail, update_re_examination, delete_re_examination
from .views import GetMedicalDetail, save_medical_detail,GetMedicalDetailDetail, update_medical_detail, delete_medical_detail

urlpatterns = [
    # for re-examination
    path('list/<int:hospital_record_id>/', GetReExaminationList.as_view(), name='re_examination_list'),
    path('create/<int:hospital_record_id>/', save_re_examination, name='create_re_examination'),
    path('list/<int:hospital_record_id>/detail/<int:id>/', GetReExaminationDetail.as_view(), name='re_examination_detail'),
    path('list/<int:hospital_record_id>/update/<int:id>/', update_re_examination, name='re_examination_update'),
    path('list/<int:hospital_record_id>/delete/<int:id>/', delete_re_examination, name='re_examination_delete'),
    # for medical detail
    path('<int:hospital_record_id>/detail/<int:id>/list-medical-detail', GetMedicalDetail.as_view(), name='medical_detail_list'),
    path('<int:hospital_record_id>/detail/<int:id>/new-medical-detail', save_medical_detail, name='create_medical_detail'),
    path('<int:hospital_record_id>/detail/<int:id>/medical-detail/<int:medical_detail_id>/', GetMedicalDetailDetail.as_view(), name='medical_detail_detail'),
    path('<int:hospital_record_id>/detail/<int:id>/medical-detail/<int:medical_detail_id>/update', update_medical_detail, name='medical_detail_update'),
    path('<int:hospital_record_id>/detail/<int:id>/medical-detail/<int:medical_detail_id>/delete', delete_medical_detail, name='medical_detail_delete'),

]

project/medical/models.py
import datetime
from django.db import models
from re_examination.models import ReExaminationModel
from django.urls import reverse

class MedicalModel(models.Model):
    name = models.CharField(max_length=100)
    effect = models.CharField(max_length=300)
    re_examinations = models.ManyToManyField(ReExaminationModel, through='MedicalDetailModel')

    class Meta:
        ordering = ['-name']
    def __str__(self):
        return f'{self.name}'
    
    def get_absolute_url(self):
        return reverse('medical_detail',kwargs={'id':self.id})

class MedicalDetailModel(models.Model):
    re_examination = models.ForeignKey(ReExaminationModel, on_delete=models.CASCADE)
    medical = models.ForeignKey(MedicalModel, on_delete=models.CASCADE)
    quantity = models.IntegerField(null=True)
    time = models.IntegerField(null=True)
    dates = models.IntegerField(null=True)

    def __str__(self):
        return f'{self.re_examination.appointment_date} - {self.medical.name}'

    class Meta:
        unique_together = (('re_examination', 'medical'),)
        ordering = ['-medical']

    def get_absolute_url(self):
        return reverse('medical_detail_detail',kwargs={'id':self.id})

project/re_examination/models.py
import datetime
from django.db import models
from hospital_record.models import HospitalRecordModel
from django.urls import reverse

class ReExaminationModel(models.Model):
    doctor = models.CharField(max_length=100)
    result = models.CharField(max_length=300)
    date = models.DateField(default=datetime.date.today, null=True)
    appointment_date = models.DateField(null=True)
    hospital_record = models.ForeignKey(HospitalRecordModel, on_delete=models.CASCADE, related_name="hr_re_examination")

    class Meta:
        ordering = ['-date']
    def __str__(self):
        return f'{self.hospital_record.disease} Re-examination'
    
    def get_absolute_url(self):
        return reverse('re_examination_detail',kwargs={'id':self.id})

project/re_examination/forms.py
from django import forms
from .models import ReExaminationModel

class PostReExamination(forms.ModelForm):
    class Meta:
        model = ReExaminationModel
        fields = ['result','date']


class PutReExamination(forms.ModelForm):
    class Meta:
        model = ReExaminationModel
        fields = ['doctor','result','date','appointment_date']

project/re_examination/templates/create_medical_detail.html
{% extends "base_project.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> New Re-examination </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'hospital_record_list' %}">Hospital Record</a></li>
            <li class="breadcrumb-item active" aria-current="page">New Re-examination</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form class="forms-sample" method="POST">
                {% csrf_token %}
                {{md_form|crispy}}

                <div class="row" style="justify-content: center">
                    <button type="submit" class="btn btn-inverse-success btn-fw col-md-4" style="margin: 0px 20px;">Save</button>
                    
                </div> 
            </form>
        </div>
    </div>
</div>
{% endblock content %}

project/re_examination/templates/create_medical_detail_form.html
{% extends "base_project.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> New Re-examination </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'hospital_record_list' %}">Hospital Record</a></li>
            <li class="breadcrumb-item active" aria-current="page">New Re-examination</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form class="forms-sample" method="POST">
                {% csrf_token %}
                {{md_form|crispy}}
                <div class="row" style="justify-content: center">
                    <button type="submit" class="btn btn-inverse-success btn-fw col-md-4" style="margin: 0px 20px;">Save</button>
                </div> 
            </form>
        </div>
    </div>
</div>
{% endblock content %}

project/re_examination/templates/create_re_examination_form.html
{% extends "base_project.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> New Re-examination </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'hospital_record_list' %}">Hospital Record</a></li>
            <li class="breadcrumb-item active" aria-current="page">New Re-examination</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form class="forms-sample" method="POST">
                {% csrf_token %}
                <!-- {{r_form|crispy}} -->
                <!-- <div id="div_id_doctor" class="form-group row"> 
                    <label for="id_doctor" class=" requiredField col-sm-3 col-form-label">Doctor<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="text" name="doctor" value="{{user.id}}" class="numberinput form-control" id="id_doctor" placeholder="" > </div>
                </div> -->
                <div id="div_id_result" class="form-group row"> 
                    <label for="id_result" class=" requiredField col-sm-3 col-form-label">Result<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="text" name="result" value="" class="numberinput form-control" required id="id_result" placeholder=""> </div>
                </div>
                <div id="div_id_date" class="form-group row"> 
                    <label for="id_date" class=" requiredField col-sm-3 col-form-label">Date<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="date" name="date" value="" class="datetimeinput form-control" required id="id_date" placeholder=""> </div>
                </div>
                <div id="div_id_appoinment_date" class="form-group row"> 
                    <label for="id_appointment_date" class=" requiredField col-sm-3 col-form-label">Appointment_date<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="date" name="appointment_date" value="" class="datetimeinput form-control" id="id_appointment_date" placeholder=""> </div>
                </div>

                <div class="row" style="justify-content: center">
                    <button type="submit" class="btn btn-inverse-success btn-fw col-md-4" style="margin: 0px 20px;">Save</button>
                    <a href="{% url 're_examination_list' hospital_record_id=hospital_record_id %}" class="btn btn-inverse-secondary btn-fw col-md-4" style="margin: 0px 20px;">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

project/re_examination/templates/detail_medical_detail.html
{% extends "base_project.html" %}
{% load crispy_forms_tags %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> Update Re-examination </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'hospital_record_list' %}">Hospital Record</a></li>
            <li class="breadcrumb-item active" aria-current="page">Update Re-examination</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form method="POST" action="{% url 'medical_detail_update' hospital_record_id=hospital_record_id id=re_examination_id medical_detail_id=medical_detail.id %}" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- {{md_form|crispy}} -->
                <!-- <div id="div_id_medical" class="form-group row"> 
                    <label for="id_medical" class=" requiredField col-sm-3 col-form-label">Medical<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="text" name="medical" value="{{medical_detail.medical}}" class="numberinput form-control" required id="id_medical" placeholder=""> </div>
                </div> -->
                <div id="div_id_quantity" class="form-group row"> 
                    <label for="id_quantity" class=" requiredField col-sm-3 col-form-label">Quantity<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="number" name="quantity" value="{{medical_detail.quantity}}" class="numberinput form-control" required id="id_quantity" placeholder=""> </div>
                </div>
                <div id="div_id_time" class="form-group row"> 
                    <label for="id_time" class=" requiredField col-sm-3 col-form-label">Time<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="number" name="time" value="{{medical_detail.time}}" class="numberinput form-control" required id="id_time" placeholder=""> </div>
                </div>

                <div class="row" style="justify-content: center">
                    <button type="submit" class="btn btn-inverse-warning btn-fw col-md-4"
                        style="margin: 0px 20px;">Update</button>
                    <a href="{% url 're_examination_list' hospital_record_id=hospital_record_id %}" class="btn btn-inverse-secondary btn-fw col-md-4"
                        style="margin: 0px 20px;">Cancel</a>
                </div>
            </form>
        </div>

    </div>
</div>
</div>
{% endblock content %}

project/re_examination/templates/detail_re_examination.html
{% extends "base_project.html" %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> Update Re-examination </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'hospital_record_list' %}">Hospital Record</a></li>
            <li class="breadcrumb-item active" aria-current="page">Update Re-examination</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form method="POST" action="{% url 're_examination_update' hospital_record_id=hospital_record_id id=re_examination.id %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div id="div_id_doctor" class="form-group row"> 
                    <label for="id_doctor" class=" requiredField col-sm-3 col-form-label">Doctor<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="text" name="doctor" value="{{re_examination.doctor}}" class="numberinput form-control" required id="id_doctor" placeholder=""> </div>
                </div>
                <div id="div_id_result" class="form-group row"> 
                    <label for="id_result" class=" requiredField col-sm-3 col-form-label">Result<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="text" name="result" value="{{re_examination.result}}" class="numberinput form-control" required id="id_result" placeholder=""> </div>
                </div>
                <div id="div_id_date" class="form-group row"> 
                    <label for="id_date" class=" requiredField col-sm-3 col-form-label">Date<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="date" name="date" value="{{re_examination.date}}" class="datetimeinput form-control" required id="id_date" placeholder=""> </div>
                </div>
                <div id="div_id_apoinment_date" class="form-group row"> 
                    <label for="id_apoinment_date" class=" requiredField col-sm-3 col-form-label">Apoinment_date<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="date" name="appointment_date" value="{{re_examination.appointment_date}}" class="datetimeinput form-control" required id="id_appointment_date" placeholder=""> </div>
                </div>

                

                <div class="row" style="justify-content: center">
                    <button type="submit" class="btn btn-inverse-warning btn-fw col-md-4"
                        style="margin: 0px 20px;">Update</button>
                    <a href="{% url 're_examination_list' hospital_record_id=hospital_record_id %}" class="btn btn-inverse-secondary btn-fw col-md-4"
                        style="margin: 0px 20px;">Cancel</a>
                </div>
            </form>
        </div>

    </div>
</div>
</div>
{% endblock content %}

project/re_examination/templates/list_medical_detail.html
{% extends "base_project.html" %}
{% load static %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> Prescription </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'hospital_record_list' %}">Hospital Record</a></li>
            <li class="breadcrumb-item active" aria-current="page">Prescription</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<!-- {% if messages %}
      {% for message in messages  %}
        <div style="color: blue;" class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
      {% endfor %}
    {% endif %} -->
    <a href="{% url 'create_medical_detail' hospital_record_id=hospital_record_id id=re_examination_id %}" class="btn btn-inverse-success btn-fw {% if not 'add_reexaminationmodel' in permissions %} d-none {% endif %}" style="margin-right: 20px; float: right; margin-bottom: 10px;">New Prescription</a>
    <!-- <button type="button" class="btn btn-inverse-success btn-fw">New physical</button> -->
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <table class="table table-striped ">
          <thead>
            <tr>
              <th> Meidcical </th>
              <th> Quantity </th>
              <th> Times </th>
              <th> Dates </th>
              <th> Update </th>
              <th> Delete </th>
              <!-- <th> Appointment date </th> -->
            </tr>
          </thead>
          <tbody>
                {% for md in medical_detail_list.results  %}
                <tr>
                    <td> {{ md.name }} </td>
                    <td> {{ md.quantity }} </td>
                    <td> {{ md.time }} </td>
                    <td> {{ md.dates }} </td>

                    <td class="{% if not 'change_medicaldetailmodel' in permissions %} d-none {% endif %}">
                      <a class="btn btn-inverse-warning btn-fw" href="{% url 'medical_detail_detail' hospital_record_id=hospital_record_id id=re_examination_id medical_detail_id=md.medical_detail_id %}" >Update</a>
                    </td>
                    <td class="{% if not 'delete_medicaldetailmodel' in permissions %} d-none {% endif %}">
                      <button type="button" class="btn btn-inverse-danger btn-fw" data-toggle="modal" data-target="#exampleModalCenter">
                        Delete
                      </button>
                      <!-- Modal -->
                      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <!-- <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5> -->
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              Are you sure delete this medical ?
                            </div>
                            <!-- for {{re.hr_re_examination.disease}} -->
                            <div class="modal-footer">
                              <button type="button" class="btn btn-inverse-secondary btn-fw col-md-4" data-dismiss="modal">Cancle</button>
                              <a class="btn btn-inverse-danger btn-fw " href="{% url 'medical_detail_delete' hospital_record_id=hospital_record_id id=re_examination_id medical_detail_id=md.medical_detail_id %}" >Delete</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </td>
                </tr>
                {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

{% endblock content %}

project/re_examination/templates/list_re_examination.html
{% extends "base_project.html" %}
{% load static %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> Re-examination </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'hospital_record_list' %}">Hospital Record</a></li>
            <li class="breadcrumb-item active" aria-current="page">Re-examination List</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<!-- {% if messages %}
      {% for message in messages  %}
        <div style="color: blue;" class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
      {% endfor %}
    {% endif %} -->
    <a href="{% url 'create_re_examination' hospital_record_id %}" class="btn btn-inverse-success btn-fw {% if not 'add_reexaminationmodel' in permissions %} d-none {% endif %}" style="margin-right: 20px; float: right; margin-bottom: 10px;">New Re-examination</a>
    <!-- <button type="button" class="btn btn-inverse-success btn-fw">New physical</button> -->
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <table class="table table-striped ">
          <thead>
            <tr>
              <th> Doctor </th>
              <th> Result </th>
              <th> Date </th>
              <th> Appointment date </th>
            </tr>
          </thead>
          <tbody>
                {% for re in re_examination.results  %}
                <tr>
                    <td> {{ re.doctor }} </td>
                    <td> {{ re.result }} </td>
                    <td> {{ re.date }} </td>
                    <td> {{ re.appointment_date }} </td>
                    <td class="{% if not 'view_medicaldetailmodel' in permissions %} d-none {% endif %}">
                      <a class="btn btn-inverse-info btn-fw" href="{% url 'medical_detail_list' hospital_record_id=hospital_record_id id=re.id %}" >Prescription</a>
                    </td>
                    <td class="{% if not 'change_reexaminationmodel' in permissions %} d-none {% endif %}">
                      <a class="btn btn-inverse-warning btn-fw" href="{% url 're_examination_detail' hospital_record_id=hospital_record_id id=re.id %}" >Update</a>
                    </td>
                    <td class="{% if not 'delete_reexaminationmodel' in permissions %} d-none {% endif %}">
                      <button type="button" class="btn btn-inverse-danger btn-fw" data-toggle="modal" data-target="#exampleModalCenter">
                        Delete
                      </button>
                      <!-- Modal -->
                      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <!-- <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5> -->
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              Are you sure delete this re-examination ?
                            </div>
                            <!-- for {{re.hr_re_examination.disease}} -->
                            <div class="modal-footer">
                              <button type="button" class="btn btn-inverse-secondary btn-fw col-md-4" data-dismiss="modal">Cancle</button>
                              <a class="btn btn-inverse-danger btn-fw " href="{% url 're_examination_delete' hospital_record_id=hospital_record_id id=re.id %}" >Delete</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </td>
                    
                </tr>
                {% endfor %}
            
          </tbody>
        </table>
      </div>
    </div>
  </div>

{% endblock content %}