project/api/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from .views import PhysicalList, PhysicalDetail, UserPhysical, FilterPhysical
from .views import VitalSignsList, VitalSignsDetail, UserVitalSigns, VitalSignsGetAll
from .views import HospitalRecordList, HospitalRecordDetail, UserHospitalRecord, FilterUserHospitalRecord, FilterAllHospitalRecord, HospitalRecordGetAll
from .views import ReExaminationList, ReExaminationDetail
from .views import MedicalList, MedicalDetail, FilterAllMedical
from .views import MedicalDetailGet, MedicalDetailPost, MedicalDetailDetail
from rest_framework_swagger.views import get_swagger_view
schema_view = get_swagger_view(title='My API document')

urlpatterns = (
    url(r'^doc/', schema_view, name='swagger'),
    # #url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
    #url(r'find$', PhysicalFilter.as_view(), name='physical'),

    url(r'physical/$', PhysicalList.as_view(), name='physical'),
    url(r'physical/(?P<pk>[0-9]+)/$', PhysicalDetail.as_view(), name='physical_detail'),
    url(r'physical/user/(?P<pk>[0-9]+)/$', UserPhysical.as_view(), name='user_physical'),
    url(r'physical/filter/(?P<pk>[0-9]+)/$', FilterPhysical.as_view(), name='physical-filter'),

    url(r'vital-signs/$', VitalSignsGetAll.as_view(), name='vital_signs'),
    url(r'vital-signs/(?P<pk>[0-9]+)/$', VitalSignsDetail.as_view(), name='vital_signs_detail'),
    url(r'vital-signs/user/(?P<pk>[0-9]+)/$', UserVitalSigns.as_view(), name='user_vital_signs'),
    
    url(r'hospital-record/$', HospitalRecordGetAll.as_view(), name='hospital_record'),
    url(r'hospital-record/(?P<pk>[0-9]+)/$', HospitalRecordDetail.as_view(), name='hospital_record_detail'),
    url(r'hospital-record/user/(?P<pk>[0-9]+)/$', UserHospitalRecord.as_view(), name="user_hospital_record"),
    url(r'hospital-record/filter/$', FilterAllHospitalRecord.as_view(), name="hospital_record_filter_all"),
    url(r'hospital-record/filter/(?P<pk>[0-9]+)/$', FilterUserHospitalRecord.as_view(), name="hospital_record_filter_user"),
    

    url(r're-examination/hospital_record/(?P<hospital_record_id>[0-9]+)/$', ReExaminationList.as_view(), name='re_examination'),
    url(r're-examination/(?P<pk>[0-9]+)/$', ReExaminationDetail.as_view(), name='re_examination_detail'),

    url(r'medical/$', MedicalList.as_view(), name='medical'),
    url(r'medical/(?P<pk>[0-9]+)/$', MedicalDetail.as_view(), name='medical_detail'),
    url(r'medical/filter$', FilterAllMedical.as_view(), name='medical_filter'),
    #url(r'medical-detail/re-examination/$', MedicalDetailList.as_view(), name='medical_detail_by_re_examination'),
    #url(r'medical-detail/re-examination/(?P<re_examination_id>[0-9]+)/$', MedicalDetailList.as_view(), name='medical_detail_by_re_examination'),
    url(r'medical-detail/get/(?P<re_examination_id>[0-9]+)/$', MedicalDetailGet.as_view(), name='medical_detail_get'),
    url(r'medical-detail/post/(?P<re_examination_id>[0-9]+)/$', MedicalDetailPost.as_view(), name='medical_detail_post'),
    url(r'medical-detail/get/(?P<re_examination_id>[0-9]+)/(?P<pk>[0-9]+)/$', MedicalDetailDetail.as_view(), name='medical_detail_post'),
)
urlpatterns = format_suffix_patterns(urlpatterns)

project/project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required

from api import urls as urls_api
from user import urls as urls_user
from physical import urls as urls_physical
from vital_signs import urls as urls_vital_signs
from hospital_record import urls as urls_hospital_record
from medical import urls as urls_medical
from re_examination import urls as urls_re_examination
# from predict import urls as urls_predict
from django.contrib.auth import views as auth_views

from user.views import Home, register, profile
from predict.views import save_symptom

urlpatterns = [
    path('toppage/', save_symptom, name='index'),
    path('home/', login_required(Home.as_view()), name='home'),
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('profile/', profile, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),

    path('admin/', admin.site.urls),
    # path('home/', include(urls_user)),
    path('api/', include(urls_api)),
    path('physical/', include(urls_physical)),
    path('vital-signs/', include(urls_vital_signs)),
    path('hospital-record/', include(urls_hospital_record)),
    path('medical/', include(urls_medical)),
    path('re-examination/', include(urls_re_examination)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/vital_signs/urls.py
from django.urls import path
from . import views
from .views import GetVitalSignsList, save_vital_signs, GetVitalSignsDetail, update_vital_signs, delete_vital

urlpatterns = [
    path('list/', GetVitalSignsList.as_view(), name='vital_signs_list'),
    path('create/', save_vital_signs, name='create_vital_signs'),
    path('detail/<int:id>/', GetVitalSignsDetail.as_view(), name='vital_signs_detail'),
    path('update/<int:id>/', update_vital_signs, name='vital_signs_update'),
    path('delete/<int:id>/', delete_vital, name='vital_signs_delete'),
]

project/vital_signs/models.py
import datetime
from django.utils import timezone,dateformat
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class VitalSignsModel(models.Model):
    temperature = models.FloatField(null=True)
    bool_pressure = models.IntegerField(null=True)
    heartbeat = models.IntegerField(null=True)
    breathing = models.IntegerField(null=True)
    time = models.DateTimeField(default=timezone.now(), null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_vital_signs")

    class Meta:
        ordering = ['-time']

    def __str__(self):
        return f'{self.user.username} Vital Signs'
    
    def get_absolute_url(self):
        return reverse('vital_signs_detail',kwargs={'id':self.id})

project/vital_signs/forms.py
from django import forms
from .models import VitalSignsModel

class PostVitalSigns(forms.ModelForm):
    class Meta:
        model = VitalSignsModel
        fields = ['temperature', 'bool_pressure','heartbeat','breathing','user']


class PutVitalSigns(forms.ModelForm):
    class Meta:
        model = VitalSignsModel
        fields = ['temperature', 'bool_pressure','heartbeat','breathing','user']

project/vital_signs/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.contrib import messages
import requests
from .forms import PostVitalSigns, PutVitalSigns
from .serializer import VitalSignsSerializer
from django.views.generic import TemplateView, DetailView
from project import utilities
import dateutil.parser

#CALL API GET LIST
class GetVitalSignsList(TemplateView):
    def get_template_names(self):
        return utilities.get_template_names(self.request.user, 'view_vitalsignsmodel', 'list_vital_signs.html')

    def get_context_data(self, *args, **kwargs):
        group = utilities.get_user_group(self.request.user)
        for gr in group:
            if str(gr)=='Doctor':
                context = {
                    'selected_tab': 'vital_signs',
                    'permissions': utilities.get_user_permissions(self.request.user),
                    'vital_signs' : get_all_vital_signs(),
            }
            else:
                context = {
                    'selected_tab': 'vital_signs',
                    'permissions': utilities.get_user_permissions(self.request.user),
                    'vital_signs' : get_vital_signs_list(self.request.user.id),
            }
            return context
        # context = {
        #     'selected_tab': 'vital_signs',
        #     'permissions': utilities.get_user_permissions(self.request.user),
        #     'vital_signs' : get_vital_signs_list(self.request.user.id),
        # }
            # return context

def get_vital_signs_list(user_id):
    url = 'http://127.0.0.1:8000/api/vital-signs/user/'+str(user_id)
    r = requests.get(url)
    vital_signs = r.json()
    vital_signs_list = vital_signs

    for vital_signs in vital_signs_list['results']:
        vital_signs['time'] = dateutil.parser.parse(vital_signs['time']).strftime("%Y-%m-%d %H:%M")

    return vital_signs_list

def get_all_vital_signs():
    url = 'http://127.0.0.1:8000/api/vital-signs/'
    r = requests.get(url)
    vital_signs = r.json()
    vital_signs_list = vital_signs

    for vital_signs in vital_signs_list['results']:
        vital_signs['time'] = dateutil.parser.parse(vital_signs['time']).strftime("%Y-%m-%d %H:%M")

    return vital_signs_list

# CALL API POST
@csrf_exempt
def save_vital_signs(request):
    if request.method == "POST" and utilities.is_permission_granted(request.user, 'add_vitalsignsmodel'):
        v_form = PostVitalSigns(request.POST)
        if v_form.is_valid():
            temperature = v_form.cleaned_data['temperature']
            bool_pressure = v_form.cleaned_data['bool_pressure']
            heartbeat = v_form.cleaned_data['heartbeat']
            breathing = v_form.cleaned_data['breathing']
            user = v_form.cleaned_data['user']
            r = requests.post('http://127.0.0.1:8000/api/vital-signs/', data = {'temperature':temperature, 
                                                                                'bool_pressure':bool_pressure, 
                                                                                'heartbeat':heartbeat, 
                                                                                'breathing':breathing,
                                                                                'user':user.id})
            if r.status_code == 200 or 201:
                data = r.json()
                print(data)
                return redirect('vital_signs_list')
        else:
        # Added else statment
            msg = 'Errors: %s' % v_form.errors.as_text()
            return HttpResponse(msg, status=400)
    else:
        v_form = PostVitalSigns()

    context =  {
        'selected_tab': 'vital_signs',
        'permissions': utilities.get_user_permissions(request.user),
        'v_form': v_form
    }

    return render(request, utilities.get_template_name(request.user, 'add_vitalsignsmodel', 'create_vital_signs_form.html'), context)

#CALL API GET DETAIL
class GetVitalSignsDetail(TemplateView):
    def get_template_names(self):
        return utilities.get_template_names(self.request.user, 'change_vitalsignsmodel', 'detail_vital_signs.html')

    def get_context_data(self, id, *args, **kwargs):
        context = {
            'selected_tab': 'vital_signs',
            'permissions': utilities.get_user_permissions(self.request.user),
            'vital_signs' : get_vital_signs_detail(id),
        }
        return context

def get_vital_signs_detail(id):
    url = 'http://127.0.0.1:8000/api/vital-signs/'+str(id)
    r = requests.get(url)
    vital_signs = r.json()
    return vital_signs

#CALL API PUT
@csrf_exempt
def update_vital_signs(request, id):
    if request.method == "POST" and utilities.is_permission_granted(request.user, 'change_vitalsignsmodel'):
        v_form = PutVitalSigns(request.POST)
        if v_form.is_valid():
            temperature = v_form.cleaned_data['temperature']
            bool_pressure = v_form.cleaned_data['bool_pressure']
            heartbeat = v_form.cleaned_data['heartbeat']
            breathing = v_form.cleaned_data['breathing']
            user = v_form.cleaned_data['user']
            print('http://127.0.0.1:8000/api/vital-signs/{}/'.format(id))
            r = requests.put('http://127.0.0.1:8000/api/vital-signs/{}/'.format(id), data = {'temperature':temperature, 
                                                                                            'bool_pressure':bool_pressure, 
                                                                                            'heartbeat':heartbeat, 
                                                                                            'breathing':breathing,
                                                                                            'user':user.id})
            if r.status_code == 200 or 201:
                data = r.json()
                print(data)
                return redirect('vital_signs_list')
        else:
        # Added else statment
            msg = 'Errors: %s' % v_form.errors.as_text()
            return HttpResponse(msg, status=400)

#CALL API DELETE
@csrf_exempt
def delete_vital(request, id):
    if utilities.is_permission_granted(request.user, 'delete_vitalsignsmodel'):
        r = requests.delete('http://127.0.0.1:8000/api/vital-signs/{}/'.format(id))

        if r.status_code == 200:
            messages.success(request, f'Delete successfully')
            data = r.json()
            print(data)

    return redirect('vital_signs_list')

project/vital_signs/templates/create_vital_signs_form.html
{% extends "base_project.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> 
      <span class="page-title-icon bg-gradient-primary text-white mr-2">
      <i class="mdi mdi-adjust"></i>
      </span> Vital Signs </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'vital_signs_list' %}">Vital Signs</a></li>
            <li class="breadcrumb-item active" aria-current="page">Vital Signs List</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form class="forms-sample" action="/vital-signs/create/" method="POST">
                {% csrf_token %}
                <!-- {{v_form|crispy}} -->
                <div id="div_id_temperature" class="form-group row"> 
                    <label for="id_temperature" class=" requiredField col-sm-3 col-form-label">Temperature<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="number" name="temperature" min="0" max="50" value="" step="any" class="numberinput form-control" required id="id_temperature" placeholder="°C"> </div>
                </div>
                <div id="div_id_bool_pressure" class="form-group row"> 
                    <label for="id_bool_pressure" class=" requiredField col-sm-3 col-form-label">Bool Pressure<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="number" name="bool_pressure" value="" class="numberinput form-control" required id="id_bool_pressure" placeholder="mmHg"> </div>
                </div>
                <div id="div_id_heartbeat" class="form-group row"> 
                    <label for="id_heartbeat" class=" requiredField col-sm-3 col-form-label">Heartbeat<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="number" name="heartbeat" value="" class="numberinput form-control" required id="id_heartbeat" placeholder="bpm"> </div>
                </div>
                <div id="div_id_breathing" class="form-group row"> 
                    <label for="id_breathing" class=" requiredField col-sm-3 col-form-label">Breathing<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="number" name="breathing" value="" class="numberinput form-control" required id="id_heartbeat" placeholder="bpm"> </div>
                </div>
                <div style="display: none;" id="div_id_user" class="form-group"> 
                    <label for="id_user" class=" requiredField">User<span class="asteriskField">*</span> </label> 
                    <div class=""> 
                        <select name="user" class="select form-control" required id="id_user" value={{user}}> 
                            <option value="{{user.id}}" selected>{{user}}</option> 
                        </select>
                    </div>
                </div>
                <!-- <input value="{{ user }}" style="display: none;" id="id_user" name="user" required id="id_user"> -->
                <div class="row" style="justify-content: center">
                    <button type="submit" class="btn btn-inverse-success btn-fw col-md-4" style="margin: 0px 20px;">Save</button>
                    <a href="{% url 'vital_signs_list' %}" class="btn btn-inverse-secondary btn-fw col-md-4" style="margin: 0px 20px;">Cancel</a>
                    <!-- <button class="btn btn-inverse-secondary btn-fw col-md-4" style="margin: 0px 20px;">Cancel</button> -->
                </div>
                <!-- <button type="submit" class="btn btn-inverse-success btn-fw col-md-6">Save</button>
                <button class="btn btn-inverse-secondary btn-fw col-md-6">Cancel</button> -->
            </form>
        </div>
    </div>
</div>
{% endblock content %}

project/vital_signs/templates/detail_vital_signs.html
{% extends "base_project.html" %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> 
      <span class="page-title-icon bg-gradient-primary text-white mr-2">
      <i class="mdi mdi-adjust"></i>
      </span> Vital Signs </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'vital_signs_list' %}">Vital Signs</a></li>
            <li class="breadcrumb-item active" aria-current="page">Vital Signs List</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form action="{% url 'vital_signs_update' id=vital_signs.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div id="div_id_temperature" class="form-group row"> 
                    <label for="id_temperature" class=" requiredField col-sm-3 col-form-label">Temperature<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="number" value="{{vital_signs.temperature}}" name="temperature" min="0" max="50" value="" step="any" class="numberinput form-control" required id="id_temperature" placeholder="°C"> </div>
                </div>
                <div id="div_id_bool_pressure" class="form-group row"> 
                    <label for="id_bool_pressure" class=" requiredField col-sm-3 col-form-label">Bool Pressure<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="number" value="{{vital_signs.bool_pressure}}" name="bool_pressure" value="" class="numberinput form-control" required id="id_bool_pressure" placeholder="mmHg"> </div>
                </div>
                <div id="div_id_heartbeat" class="form-group row"> 
                    <label for="id_heartbeat" class=" requiredField col-sm-3 col-form-label">Heartbeat<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="number" value="{{vital_signs.heartbeat}}" name="heartbeat" value="" class="numberinput form-control" required id="id_heartbeat" placeholder="bpm"> </div>
                </div>
                <div id="div_id_breathing" class="form-group row"> 
                    <label for="id_breathing" class=" requiredField col-sm-3 col-form-label">Breathing<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="number" value="{{vital_signs.breathing}}" name="breathing" value="" class="numberinput form-control" required id="id_heartbeat" placeholder="bpm"> </div>
                </div>
                <div style="display: none;" id="div_id_user" class="form-group"> 
                    <label for="id_user" class=" requiredField">User<span class="asteriskField">*</span> </label> 
                    <div class=""> 
                        <select name="user" class="select form-control" required id="id_user" value={{user}}> 
                            <option value="{{user.id}}" selected>{{user}}</option> 
                        </select>
                    </div>
                </div>
                <div class="row" style="justify-content: center">
                    <button type="submit" class="btn btn-inverse-warning btn-fw col-md-4"
                        style="margin: 0px 20px;">Update</button>
                    <a href="{% url 'vital_signs_list' %}" class="btn btn-inverse-secondary btn-fw col-md-4"
                        style="margin: 0px 20px;">Cancel</a>
                    <!-- <button class="btn btn-inverse-secondary btn-fw col-md-4" style="margin: 0px 20px;">Cancel</button> -->
                </div>

                <!-- <button type="submit" class="btn btn-inverse-warning btn-fw col-md-12">Update</button> -->
            </form>
        </div>

    </div>
</div>
</div>
{% endblock content %}

project/vital_signs/templates/list_vital_signs.html
{% extends "base_project.html" %}
{% load static %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> 
      <span class="page-title-icon bg-gradient-primary text-white mr-2">
      <i class="mdi mdi-adjust"></i>
      </span> Vital Signs </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'vital_signs_list' %}">Vital Signs</a></li>
            <li class="breadcrumb-item active" aria-current="page">Vital Signs List</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<!-- {% if messages %}
      {% for message in messages  %}
        <div style="color: blue;" class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
      {% endfor %}
    {% endif %} -->
    <a href="{% url 'create_vital_signs' %}" class="btn btn-inverse-success btn-fw {% if not 'add_vitalsignsmodel' in permissions %} d-none {% endif %}" style="margin-right: 20px; float: right; margin-bottom: 10px;">New Vital Signs</a>
    <!-- <button type="button" class="btn btn-inverse-success btn-fw">New physical</button> -->
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <table class="table table-striped ">
          <thead>
            <tr>
              <!-- <th> Patient </th> -->
              <th> Time </th>
              <th> Temperature <br> (°C) </th>
              <th> Bool Pressure <br> (mmHg) </th>
              <th> Heartbeat <br> (bpm) </th>
              <th> Breathing <br> (per minute)</th>
            </tr>
          </thead>
          <tbody>
                {% for vs in vital_signs.results  %}
                <tr>
                    <!-- <td> {{ vs.username }} </td> -->
                    <td> {{ vs.time }} </td>
                    <td> {{ vs.temperature }} </td>
                    <td> {{ vs.bool_pressure }} </td>
                    <td> {{ vs.heartbeat }} </td>
                    <td> {{ vs.breathing }} </td>
                    <td class="{% if not 'change_vitalsignsmodel' in permissions %} d-none {% endif %}">
                      <a class="btn btn-inverse-warning btn-fw" href="{% url 'vital_signs_detail' id=vs.id %}" >Update</a>
                    </td>
                    <td class="{% if not 'delete_vitalsignsmodel' in permissions %} d-none {% endif %}">
                      <button type="button" class="btn btn-inverse-danger btn-fw" data-toggle="modal" data-target="#exampleModalCenter">
                        Delete
                      </button>
                      <!-- Modal -->
                      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <!-- <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5> -->
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              Are you sure delete the physical created on {{vs.time}} ?
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-inverse-secondary btn-fw col-md-4" data-dismiss="modal">Cancle</button>
                              <a class="btn btn-inverse-danger btn-fw " href="{% url 'vital_signs_delete' id=vs.id %}" >Delete</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </td>
                    
                </tr>
                {% endfor %}
            
          </tbody>
        </table>
      </div>
    </div>
  </div>

{% endblock content %}