project/api/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from .views import PhysicalList, PhysicalDetail, UserPhysical, FilterPhysical
from .views import VitalSignsList, VitalSignsDetail, UserVitalSigns, VitalSignsGetAll
from .views import HospitalRecordList, HospitalRecordDetail, UserHospitalRecord, FilterUserHospitalRecord, FilterAllHospitalRecord, HospitalRecordGetAll
from .views import ReExaminationList, ReExaminationDetail
from .views import MedicalList, MedicalDetail, FilterAllMedical
from .views import MedicalDetailGet, MedicalDetailPost, MedicalDetailDetail
from rest_framework_swagger.views import get_swagger_view
schema_view = get_swagger_view(title='My API document')

urlpatterns = (
    url(r'^doc/', schema_view, name='swagger'),
    # #url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
    #url(r'find$', PhysicalFilter.as_view(), name='physical'),

    url(r'physical/$', PhysicalList.as_view(), name='physical'),
    url(r'physical/(?P<pk>[0-9]+)/$', PhysicalDetail.as_view(), name='physical_detail'),
    url(r'physical/user/(?P<pk>[0-9]+)/$', UserPhysical.as_view(), name='user_physical'),
    url(r'physical/filter/(?P<pk>[0-9]+)/$', FilterPhysical.as_view(), name='physical-filter'),

    url(r'vital-signs/$', VitalSignsGetAll.as_view(), name='vital_signs'),
    url(r'vital-signs/(?P<pk>[0-9]+)/$', VitalSignsDetail.as_view(), name='vital_signs_detail'),
    url(r'vital-signs/user/(?P<pk>[0-9]+)/$', UserVitalSigns.as_view(), name='user_vital_signs'),
    
    url(r'hospital-record/$', HospitalRecordGetAll.as_view(), name='hospital_record'),
    url(r'hospital-record/(?P<pk>[0-9]+)/$', HospitalRecordDetail.as_view(), name='hospital_record_detail'),
    url(r'hospital-record/user/(?P<pk>[0-9]+)/$', UserHospitalRecord.as_view(), name="user_hospital_record"),
    url(r'hospital-record/filter/$', FilterAllHospitalRecord.as_view(), name="hospital_record_filter_all"),
    url(r'hospital-record/filter/(?P<pk>[0-9]+)/$', FilterUserHospitalRecord.as_view(), name="hospital_record_filter_user"),
    

    url(r're-examination/hospital_record/(?P<hospital_record_id>[0-9]+)/$', ReExaminationList.as_view(), name='re_examination'),
    url(r're-examination/(?P<pk>[0-9]+)/$', ReExaminationDetail.as_view(), name='re_examination_detail'),

    url(r'medical/$', MedicalList.as_view(), name='medical'),
    url(r'medical/(?P<pk>[0-9]+)/$', MedicalDetail.as_view(), name='medical_detail'),
    url(r'medical/filter$', FilterAllMedical.as_view(), name='medical_filter'),
    #url(r'medical-detail/re-examination/$', MedicalDetailList.as_view(), name='medical_detail_by_re_examination'),
    #url(r'medical-detail/re-examination/(?P<re_examination_id>[0-9]+)/$', MedicalDetailList.as_view(), name='medical_detail_by_re_examination'),
    url(r'medical-detail/get/(?P<re_examination_id>[0-9]+)/$', MedicalDetailGet.as_view(), name='medical_detail_get'),
    url(r'medical-detail/post/(?P<re_examination_id>[0-9]+)/$', MedicalDetailPost.as_view(), name='medical_detail_post'),
    url(r'medical-detail/get/(?P<re_examination_id>[0-9]+)/(?P<pk>[0-9]+)/$', MedicalDetailDetail.as_view(), name='medical_detail_post'),
)
urlpatterns = format_suffix_patterns(urlpatterns)

project/hospital_record/urls.py
from django.urls import path
from . import views
from .views import GetHospitalRecordList, FilterHospitalRecordList, save_hospital_record, delete_hospital_record, GetHospitalRecordDetail, update_hospital_record

urlpatterns = [
    path('list/', GetHospitalRecordList.as_view(), name='hospital_record_list'),
    path('filter/', FilterHospitalRecordList.as_view(), name='hospital_record_filter'),
    path('create/', save_hospital_record, name='create_hospital_record'),
    path('detail/<int:id>/', GetHospitalRecordDetail.as_view(), name='hospital_record_detail'),
    path('update/<int:id>/', update_hospital_record, name='hospital_record_update'),
    path('delete/<int:id>/', delete_hospital_record, name='hospital_record_delete'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required

from api import urls as urls_api
from user import urls as urls_user
from physical import urls as urls_physical
from vital_signs import urls as urls_vital_signs
from hospital_record import urls as urls_hospital_record
from medical import urls as urls_medical
from re_examination import urls as urls_re_examination
# from predict import urls as urls_predict
from django.contrib.auth import views as auth_views

from user.views import Home, register, profile
from predict.views import save_symptom

urlpatterns = [
    path('toppage/', save_symptom, name='index'),
    path('home/', login_required(Home.as_view()), name='home'),
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('profile/', profile, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),

    path('admin/', admin.site.urls),
    # path('home/', include(urls_user)),
    path('api/', include(urls_api)),
    path('physical/', include(urls_physical)),
    path('vital-signs/', include(urls_vital_signs)),
    path('hospital-record/', include(urls_hospital_record)),
    path('medical/', include(urls_medical)),
    path('re-examination/', include(urls_re_examination)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/hospital_record/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.urls import reverse

class HospitalRecordModel(models.Model):
    hospital = models.CharField(max_length=300)
    disease = models.CharField(max_length=300, null=True)
    start_time = models.DateField(default=datetime.date.today, null=True)
    STATUS_CHOICES = (
        ('In process', 'In process'),
        ('Done', 'Done'),
    )
    status = models.CharField(max_length=11, choices=STATUS_CHOICES, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_hospital_record")

    class Meta:
        ordering = ['-start_time']

    def __str__(self):
        return f'{self.user.username}  hospital record {self.disease}' 
    
    def get_absolute_url(self):
        return reverse('hospital_record_detail',kwargs={'id':self.id})

project/hospital_record/forms.py
from django import forms
from .models import HospitalRecordModel

class PostHospitalRecord(forms.ModelForm):
    class Meta:
        model = HospitalRecordModel
        fields = ['hospital','disease','start_time','status','user']


class PutHospitalRecord(forms.ModelForm):
    class Meta:
        model = HospitalRecordModel
        fields = ['hospital','disease','start_time','status','user']

project/hospital_record/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.contrib import messages
import requests
from .forms import PostHospitalRecord, PutHospitalRecord
from .serializer import HospitalRecordSerializer
from django.views.generic import TemplateView, DetailView
from project import utilities

#CALL API GET LIST
class GetHospitalRecordList(TemplateView):
    def get_template_names(self):
        return utilities.get_template_names(self.request.user, 'view_hospitalrecordmodel', 'list_hospital_record.html')

    def get_context_data(self, *args, **kwargs):
        group = utilities.get_user_group(self.request.user)
        for gr in group:
            if str(gr)=='Doctor':
                print("okkkkkkkkkkkkkkkkkkkkkkk")
                context = {
                    'selected_tab': 'hospital_record',
                    'permissions': utilities.get_user_permissions(self.request.user),
                    'hospital_record' : get_all_hospital_record(self.request.user.id),
            }
            else:
                print("---------------------------")
                context = {
                    'selected_tab': 'hospital_record',
                    'permissions': utilities.get_user_permissions(self.request.user),
                    'hospital_record' : get_hospital_record_list(self.request.user.id),
            }
            return context

def get_hospital_record_list(user_id):
    url = 'http://127.0.0.1:8000/api/hospital-record/user/'+str(user_id)
    r = requests.get(url)
    hospital_record = r.json()
    hospital_record_list = hospital_record
    return hospital_record_list

def get_all_hospital_record(user_id):
    url = 'http://127.0.0.1:8000/api/hospital-record/'
    r = requests.get(url)
    hospital_record = r.json()
    hospital_record_list = hospital_record
    return hospital_record_list

#CALL API GET FILTER LIST
class FilterHospitalRecordList(TemplateView):
    def get_template_names(self):
        return utilities.get_template_names(self.request.user, 'view_hospitalrecordmodel', 'list_hospital_record.html')

    def get_context_data(self, *args, **kwargs):
        group = utilities.get_user_group(self.request.user)
        for gr in group:
            if str(gr)=='Doctor':
                context = {
                    'selected_tab': 'hospital_record',
                    'permissions': utilities.get_user_permissions(self.request.user),
                    'hospital_record' : filter_all_hospital_record(self.request),
            }
            else:
                context = {
                    'selected_tab': 'hospital_record',
                    'permissions': utilities.get_user_permissions(self.request.user),
                    'hospital_record' : filter_user_hospital_record(self.request.user.id, self.request),
            }
            return context
        # print("--------------")
        # context = {
        #     'selected_tab': 'hospital_record',
        #     'permissions': utilities.get_user_permissions(self.request.user),
        #     'hospital_record' : filter_hospital_record_list(self.request.user.id, self.request),
        # }
        # print(str(self.request)+"=======================")
        # return context

def filter_all_hospital_record(request):
    disease=request.GET.get('disease')
    print(str(disease)+"--------------")
    url = 'http://127.0.0.1:8000/api/hospital-record/filter?disease={}'.format(disease)
    r = requests.get(url)
    hospital_record = r.json()
    hospital_record_list = hospital_record
    return hospital_record_list

def filter_user_hospital_record(user_id, request):
    disease=request.GET.get('disease')
    print(str(disease)+"--------------")
    url = 'http://127.0.0.1:8000/api/hospital-record/filter/{}?disease={}'.format(user_id, disease)
    r = requests.get(url)
    hospital_record = r.json()
    hospital_record_list = hospital_record
    return hospital_record_list

# CALL API POST
@csrf_exempt
def save_hospital_record(request):
    if request.method == "POST" and utilities.is_permission_granted(request.user, 'add_hospitalrecordmodel'):
        h_form = PostHospitalRecord(request.POST)
        if h_form.is_valid():
            hospital = h_form.cleaned_data['hospital']
            disease = h_form.cleaned_data['disease']
            start_time = h_form.cleaned_data['start_time']
            status = h_form.cleaned_data['status']
            user = h_form.cleaned_data['user']
            r = requests.post('http://127.0.0.1:8000/api/hospital-record/', data = {'hospital':hospital,
                                                                                    'disease':disease,
                                                                                    'start_time':start_time,
                                                                                    'status':status,
                                                                                    'user':user.id})
            if r.status_code == 200 or 201:
                data = r.json()
                print(data)
                return redirect('hospital_record_list')
        else:
        # Added else statment
            msg = 'Errors: %s' % h_form.errors.as_text()
            return HttpResponse(msg, status=400)
    else:
        h_form = PostHospitalRecord()

    context =  {
        'selected_tab': 'hospital_record',
        'permissions': utilities.get_user_permissions(request.user),
        'h_form': h_form
    }

    return render(request, utilities.get_template_name(request.user, 'add_hospitalrecordmodel', 'create_hospital_record_form.html'), context)

#CALL API GET DETAIL
class GetHospitalRecordDetail(TemplateView):
    def get_template_names(self):
        return utilities.get_template_names(self.request.user, 'change_hospitalrecordmodel', 'detail_hospital_record.html')

    def get_context_data(self, id, *args, **kwargs):
        context = {
            'selected_tab': 'hospital_record',
            'permissions': utilities.get_user_permissions(self.request.user),
            'hospital_record' : get_hospital_record_detail(id),
        }
        return context

def get_hospital_record_detail(id):
    url = 'http://127.0.0.1:8000/api/hospital-record/'+str(id)
    r = requests.get(url)
    hospital_record = r.json()
    return hospital_record

#CALL API PUT
@csrf_exempt
def update_hospital_record(request, id):
    if request.method == "POST" and utilities.is_permission_granted(request.user, 'change_hospitalrecordmodel'):
        h_form = PutHospitalRecord(request.POST)
        if h_form.is_valid():
            hospital = h_form.cleaned_data['hospital']
            disease = h_form.cleaned_data['disease']
            start_time = h_form.cleaned_data['start_time']
            status = h_form.cleaned_data['status']
            user = h_form.cleaned_data['user']
            r = requests.put('http://127.0.0.1:8000/api/hospital-record/{}/'.format(id), data = {'hospital':hospital,
                                                                                                'disease':disease,
                                                                                                'start_time':start_time,
                                                                                                'status':status,
                                                                                                'user':user.id})
            if r.status_code == 200 or 201:
                data = r.json()
                print(data)
                return redirect('hospital_record_list')
        else:
        # Added else statment
            msg = 'Errors: %s' % h_form.errors.as_text()
            return HttpResponse(msg, status=400)

#CALL API DELETE
@csrf_exempt
def delete_hospital_record(request, id):
    if utilities.is_permission_granted(request.user, 'delete_hospitalrecordmodel'):
        r = requests.delete('http://127.0.0.1:8000/api/hospital-record/{}/'.format(id))

        if r.status_code == 200:
            messages.success(request, f'Delete successfully')
            data = r.json()
            print(data)

    return redirect('hospital_record_list')

project/hospital_record/templates/create_hospital_record_form.html
{% extends "base_project.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> <span class="page-title-icon bg-gradient-primary text-white mr-2">
      <i class="mdi mdi-animation"></i>
    </span> Hospital Record </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'hospital_record_list' %}">Hospital Record</a></li>
            <li class="breadcrumb-item active" aria-current="page">Hospital Record List</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form class="forms-sample" action="/hospital-record/create/" method="POST">
                {% csrf_token %}
                {{h_form|crispy}}
                <!-- <div id="div_id_hospital" class="form-group row"> 
                    <label for="id_hospital" class=" requiredField col-sm-3 col-form-label">Hospital<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="text" name="hospital" value="" class="numberinput form-control" required id="id_hospital" placeholder=""> </div>
                </div>
                <div id="div_id_disease" class="form-group row"> 
                    <label for="id_disease" class=" requiredField col-sm-3 col-form-label">Disease<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="text" name="disease" value="" class="numberinput form-control" required id="id_disease" placeholder=""> </div>
                </div>
                <div id="div_id_start_time" class="form-group row"> 
                    <label for="id_start_time" class=" requiredField col-sm-3 col-form-label">Start Time<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="date" name="start_time" value="" class="datetimeinput form-control" required id="id_start_time" placeholder=""> </div>
                </div>
                <div id="div_id_status" class="form-group row"> 
                    <label for="id_status" class=" requiredField col-sm-3 col-form-label">Status<span class="asteriskField">*</span> </label> 
                    <div class="col-sm-9"> 
                        <select name="status" class="select form-control" required id="id_status"> 
                            <option value="" selected>---------</option> 
                            <option value="In process">In process</option> 
                            <option value="Done">Done</option>
                        </select> 
                    </div> 
                </div>
    
                <div style="display: none;" id="div_id_user" class="form-group"> 
                    <label for="id_user" class=" requiredField">User<span class="asteriskField">*</span> </label> 
                    <div class=""> 
                        <select name="user" class="select form-control" required id="id_user" value={{user}}> 
                            <option value="{{user.id}}" selected>{{user}}</option> 
                        </select>
                    </div>
                </div> -->
                <!-- <input value="{{ user }}" style="display: none;" id="id_user" name="user" required id="id_user"> -->
                <div class="row" style="justify-content: center">
                    <button type="submit" class="btn btn-inverse-success btn-fw col-md-4" style="margin: 0px 20px;">Save</button>
                    <a href="{% url 'hospital_record_list' %}" class="btn btn-inverse-secondary btn-fw col-md-4" style="margin: 0px 20px;">Cancel</a>
                    <!-- <button class="btn btn-inverse-secondary btn-fw col-md-4" style="margin: 0px 20px;">Cancel</button> -->
                </div>
                <!-- <button type="submit" class="btn btn-inverse-success btn-fw col-md-6">Save</button>
                <button class="btn btn-inverse-secondary btn-fw col-md-6">Cancel</button> -->
            </form>
        </div>
    </div>
</div>
{% endblock content %}

project/hospital_record/templates/detail_hospital_record.html
{% extends "base_project.html" %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> <span class="page-title-icon bg-gradient-primary text-white mr-2">
      <i class="mdi mdi-animation"></i>
    </span> Hospital Record </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'hospital_record_list' %}">Hospital Record</a></li>
            <li class="breadcrumb-item active" aria-current="page">Hospital Record List</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form action="{% url 'hospital_record_update' id=hospital_record.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div id="div_id_hospital" class="form-group row"> 
                    <label for="id_hospital" class=" requiredField col-sm-3 col-form-label">Hospital<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="text" value="{{hospital_record.hospital}}" name="hospital" value="" class="numberinput form-control" required id="id_hospital" placeholder=""> </div>
                </div>
                <div id="div_id_disease" class="form-group row"> 
                    <label for="id_disease" class=" requiredField col-sm-3 col-form-label">Disease<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="text" name="disease" value="{{hospital_record.disease}}" class="numberinput form-control" required id="id_disease" placeholder=""> </div>
                </div>
                <div id="div_id_start_time" class="form-group row"> 
                    <label for="id_start_time" class=" requiredField col-sm-3 col-form-label">Start Time<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="date" value="{{hospital_record.start_time}}" name="start_time" value="{{hospital_record.start_time}}" class="datetimeinput form-control" required id="id_start_time" placeholder=""> </div>
                </div>
                <div id="div_id_status" class="form-group row"> 
                    <label for="id_status" class=" requiredField col-sm-3 col-form-label">Status<span class="asteriskField">*</span> </label> 
                    <div class="col-sm-9"> 
                        <select name="status" class="select form-control" required id="id_status"> 
                            <option value="In process">In process</option> 
                            <option value="Done">Done</option>
                        </select> 
                    </div> 
                </div>
                <div style="display: none;" id="div_id_user" class="form-group"> 
                    <label for="id_user" class=" requiredField">User<span class="asteriskField">*</span> </label> 
                    <div class=""> 
                        <select name="user" class="select form-control" required id="id_user" value={{user}}> 
                            <option value="{{user.id}}" selected>{{user}}</option> 
                        </select>
                    </div>
                </div>
                <div class="row" style="justify-content: center">
                    <button type="submit" class="btn btn-inverse-warning btn-fw col-md-4"
                        style="margin: 0px 20px;">Update</button>
                    <a href="{% url 'hospital_record_list' %}" class="btn btn-inverse-secondary btn-fw col-md-4"
                        style="margin: 0px 20px;">Cancel</a>
                    <!-- <button class="btn btn-inverse-secondary btn-fw col-md-4" style="margin: 0px 20px;">Cancel</button> -->
                </div>

                <!-- <button type="submit" class="btn btn-inverse-warning btn-fw col-md-12">Update</button> -->
            </form>
        </div>

    </div>
</div>
</div>
{% endblock content %}

project/hospital_record/templates/list_hospital_record.html
{% extends "base_project.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block search_form %}
<div class="search-field d-none d-md-block">
  <form class="d-flex align-items-center h-100" action="{% url 'hospital_record_filter' %}" >
    {% csrf_token %}
    <div class="input-group" id="diease">
      <div class="input-group-prepend bg-transparent">
        <i class="input-group-text border-0 mdi mdi-magnify"></i>
      </div>
      <input type="text" class="form-control bg-transparent border-0" id="disease" name="disease" placeholder="Search Disease">
    </div>
  </form>
</div>
{% endblock search_form %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> <span class="page-title-icon bg-gradient-primary text-white mr-2">
      <i class="mdi mdi-animation"></i>
    </span> Hospital Record </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'hospital_record_list' %}">Hospital Record</a></li>
            <li class="breadcrumb-item active" aria-current="page">Hospital Record List</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<!-- {% if messages %}
      {% for message in messages  %}
        <div style="color: blue;" class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
      {% endfor %}
    {% endif %} -->
    <a href="{% url 'create_hospital_record' %}" class="btn btn-inverse-success btn-fw {% if not 'add_hospitalrecordmodel' in permissions %} d-none {% endif %}" style="margin-right: 20px; float: right; margin-bottom: 10px;">New Hospital Record</a>
    <!-- <button type="button" class="btn btn-inverse-success btn-fw">New physical</button> -->
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <table class="table table-striped ">
          <thead>
            <tr>
              <!-- <th> Patient </th> -->
              <th> Disease </th>
              <th> Start Time </th>
              <th> Status </th>
            </tr>
          </thead>
          <tbody>
                {% for hr in hospital_record.results  %}
                <tr>
                    <!-- <td> {{ hr.username }} </td> -->
                    <td> {{ hr.disease }} </td>
                    <td> {{ hr.start_time }} </td>
                    <td> {{ hr.status }} </td>
                    <td class="{% if not 'view_reexaminationmodel' in permissions %} d-none {% endif %}">
                      <a class="btn btn-inverse-info btn-fw" href="{% url 're_examination_list' hospital_record_id=hr.id %}" >Detail</a>
                    </td>
                    <td class="{% if not 'change_hospitalrecordmodel' in permissions %} d-none {% endif %}">
                      <a class="btn btn-inverse-warning btn-fw" href="{% url 'hospital_record_detail' id=hr.id %}" >Update</a>
                    </td>
                    <td class="{% if not 'delete_hospitalrecordmodel' in permissions %} d-none {% endif %}">
                      <button type="button" class="btn btn-inverse-danger btn-fw" data-toggle="modal" data-target="#exampleModalCenter">
                        Delete
                      </button>
                      <!-- Modal -->
                      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <!-- <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5> -->
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              Are you sure delete this hospital record for {{ hr.disease }} ?
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-inverse-secondary btn-fw col-md-4" data-dismiss="modal">Cancle</button>
                              <a class="btn btn-inverse-danger btn-fw " href="{% url 'hospital_record_delete' id=hr.id %}" >Delete</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </td>
                    
                </tr>
                {% endfor %}
            
          </tbody>
        </table>
      </div>
    </div>
  </div>

{% endblock content %}