project/api/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from .views import PhysicalList, PhysicalDetail, UserPhysical, FilterPhysical
from .views import VitalSignsList, VitalSignsDetail, UserVitalSigns, VitalSignsGetAll
from .views import HospitalRecordList, HospitalRecordDetail, UserHospitalRecord, FilterUserHospitalRecord, FilterAllHospitalRecord, HospitalRecordGetAll
from .views import ReExaminationList, ReExaminationDetail
from .views import MedicalList, MedicalDetail, FilterAllMedical
from .views import MedicalDetailGet, MedicalDetailPost, MedicalDetailDetail
from rest_framework_swagger.views import get_swagger_view
schema_view = get_swagger_view(title='My API document')

urlpatterns = (
    url(r'^doc/', schema_view, name='swagger'),
    # #url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
    #url(r'find$', PhysicalFilter.as_view(), name='physical'),

    url(r'physical/$', PhysicalList.as_view(), name='physical'),
    url(r'physical/(?P<pk>[0-9]+)/$', PhysicalDetail.as_view(), name='physical_detail'),
    url(r'physical/user/(?P<pk>[0-9]+)/$', UserPhysical.as_view(), name='user_physical'),
    url(r'physical/filter/(?P<pk>[0-9]+)/$', FilterPhysical.as_view(), name='physical-filter'),

    url(r'vital-signs/$', VitalSignsGetAll.as_view(), name='vital_signs'),
    url(r'vital-signs/(?P<pk>[0-9]+)/$', VitalSignsDetail.as_view(), name='vital_signs_detail'),
    url(r'vital-signs/user/(?P<pk>[0-9]+)/$', UserVitalSigns.as_view(), name='user_vital_signs'),
    
    url(r'hospital-record/$', HospitalRecordGetAll.as_view(), name='hospital_record'),
    url(r'hospital-record/(?P<pk>[0-9]+)/$', HospitalRecordDetail.as_view(), name='hospital_record_detail'),
    url(r'hospital-record/user/(?P<pk>[0-9]+)/$', UserHospitalRecord.as_view(), name="user_hospital_record"),
    url(r'hospital-record/filter/$', FilterAllHospitalRecord.as_view(), name="hospital_record_filter_all"),
    url(r'hospital-record/filter/(?P<pk>[0-9]+)/$', FilterUserHospitalRecord.as_view(), name="hospital_record_filter_user"),
    

    url(r're-examination/hospital_record/(?P<hospital_record_id>[0-9]+)/$', ReExaminationList.as_view(), name='re_examination'),
    url(r're-examination/(?P<pk>[0-9]+)/$', ReExaminationDetail.as_view(), name='re_examination_detail'),

    url(r'medical/$', MedicalList.as_view(), name='medical'),
    url(r'medical/(?P<pk>[0-9]+)/$', MedicalDetail.as_view(), name='medical_detail'),
    url(r'medical/filter$', FilterAllMedical.as_view(), name='medical_filter'),
    #url(r'medical-detail/re-examination/$', MedicalDetailList.as_view(), name='medical_detail_by_re_examination'),
    #url(r'medical-detail/re-examination/(?P<re_examination_id>[0-9]+)/$', MedicalDetailList.as_view(), name='medical_detail_by_re_examination'),
    url(r'medical-detail/get/(?P<re_examination_id>[0-9]+)/$', MedicalDetailGet.as_view(), name='medical_detail_get'),
    url(r'medical-detail/post/(?P<re_examination_id>[0-9]+)/$', MedicalDetailPost.as_view(), name='medical_detail_post'),
    url(r'medical-detail/get/(?P<re_examination_id>[0-9]+)/(?P<pk>[0-9]+)/$', MedicalDetailDetail.as_view(), name='medical_detail_post'),
)
urlpatterns = format_suffix_patterns(urlpatterns)

project/physical/urls.py
from django.urls import path
from .views import save_physical, GetPhysicalList, FilterPhysicalList, GetPhysicalDetail, update_physical, delete_physical

urlpatterns = [
    path('create/', save_physical, name='create_physical'),
    path('list/', GetPhysicalList.as_view(), name='physical_list'),
    path('filter/', FilterPhysicalList.as_view(), name='physical_filter'),
    path('detail/<int:id>/', GetPhysicalDetail.as_view(), name='physical_detail'),
    path('update/<int:id>/', update_physical, name='physical_update'),
    path('delete/<int:id>/', delete_physical, name='physical_delete'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required

from api import urls as urls_api
from user import urls as urls_user
from physical import urls as urls_physical
from vital_signs import urls as urls_vital_signs
from hospital_record import urls as urls_hospital_record
from medical import urls as urls_medical
from re_examination import urls as urls_re_examination
# from predict import urls as urls_predict
from django.contrib.auth import views as auth_views

from user.views import Home, register, profile
from predict.views import save_symptom

urlpatterns = [
    path('toppage/', save_symptom, name='index'),
    path('home/', login_required(Home.as_view()), name='home'),
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('profile/', profile, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),

    path('admin/', admin.site.urls),
    # path('home/', include(urls_user)),
    path('api/', include(urls_api)),
    path('physical/', include(urls_physical)),
    path('vital-signs/', include(urls_vital_signs)),
    path('hospital-record/', include(urls_hospital_record)),
    path('medical/', include(urls_medical)),
    path('re-examination/', include(urls_re_examination)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/physical/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class PhysicalModel(models.Model):
    height = models.FloatField(null=True)
    weight = models.FloatField(null=True)
    date = models.DateField(default=datetime.date.today, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_physical")

    class Meta:
        ordering = ['-date']
    def __str__(self):
        return f'{self.user.username} Physical'
    
    def get_absolute_url(self):
        return reverse('physical_detail',kwargs={'id':self.id})

project/physical/forms.py
from django import forms
from .models import PhysicalModel


class PostPhysical(forms.ModelForm):
    # user = forms.CharField()

    class Meta:
        model = PhysicalModel
        fields = ['height', 'weight', 'date', 'user']


class PutPhysical(forms.ModelForm):
    class Meta:
        model = PhysicalModel
        fields = ['height', 'weight', 'date', 'user']

# user = forms.IntegerField(widget= forms.TextInput
# (attrs={'class':'numberinput form-control'}))

project/physical/views.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
import requests
from .forms import PostPhysical, PutPhysical
from django.views.generic import TemplateView
from project import utilities


# CALL API GET LIST
class GetPhysicalList(TemplateView):
    def get_template_names(self):
        return utilities.get_template_names(self.request.user, 'view_physicalmodel', 'list_physical.html')

    def get_context_data(self, *args, **kwargs):
        context = {
            'selected_tab': 'physical',
            'permissions': utilities.get_user_permissions(self.request.user),
            'physical' : get_physical_list(self.request.user.id),
        }
        return context


def get_physical_list(user_id):
    url = 'http://127.0.0.1:8000/api/physical/user/'+str(user_id)
    r = requests.get(url)
    physical = r.json()
    physical_list = physical
    print(physical_list)
    return physical_list


# CALL API FILLTER PHYSICAL
class FilterPhysicalList(TemplateView):
    def get_template_names(self):
        return utilities.get_template_names(self.request.user, 'view_physicalmodel', 'list_physical.html')

    def get_context_data(self, *args, **kwargs):
        context = {
            'selected_tab': 'physical',
            'permissions': utilities.get_user_permissions(self.request.user),
            'physical' : filter_physical_list(self.request.user.id, self.request),
        }
        return context


def filter_physical_list(user_id, request):
    height=request.GET.get('height')
    url = 'http://127.0.0.1:8000/api/physical/filter/{}?height={}'.format(user_id, height)
    r = requests.get(url)
    physical = r.json()
    physical_list = physical
    return physical_list

# CALL API POST
@csrf_exempt
def save_physical(request):
    if request.method == "POST" and utilities.is_permission_granted(request.user, 'add_physicalmodel'):
        form = PostPhysical(request.POST)
        if form.is_valid():
            height = form.cleaned_data['height']
            weight = form.cleaned_data['weight']
            date = form.cleaned_data['date']
            user = form.cleaned_data['user']
            r = requests.post('http://127.0.0.1:8000/api/physical/', data = {'height':height, 'weight':weight, 'date':date, 'user':user.id})
            if r.status_code == 200 or 201:
                data = r.json()
                print(data)
                return redirect('physical_list')
            else:
                msg = r.json()
                return HttpResponse(msg)
        else:
            # Added else statement
            msg = 'Errors: %s' % form.errors.as_text()
            return HttpResponse(msg, status=400)
    else:
        form = PostPhysical()

    context = {
        'selected_tab': 'physical',
        'permissions': utilities.get_user_permissions(request.user),
        'form': form
    }

    return render(request, utilities.get_template_name(request.user, 'add_physicalmodel', 'create_form.html'), context)


# CALL API GET DETAIL
class GetPhysicalDetail(TemplateView):
    def get_template_names(self):
        return utilities.get_template_names(self.request.user, 'change_physicalmodel', 'detail_physical.html')

    def get_context_data(self, id, *args, **kwargs):
        context = {
            'selected_tab': 'physical',
            'permissions': utilities.get_user_permissions(self.request.user),
            'physical': get_physical_detail(id)
        }
        return context


def get_physical_detail(id):
    url = 'http://127.0.0.1:8000/api/physical/'+str(id)
    r = requests.get(url)
    physical = r.json()
    print(physical)
    return physical

#CALL API PUT
@csrf_exempt
def update_physical(request, id):
    if request.method == "POST" and utilities.is_permission_granted(request.user, 'change_physicalmodel'):
        form = PutPhysical(request.POST)
        #form = PutPhysical(request.POST,instance=request.physical)
        if form.is_valid():
            height = form.cleaned_data['height']
            weight = form.cleaned_data['weight']
            date = form.cleaned_data['date']
            user = form.cleaned_data['user']
            r = requests.put('http://127.0.0.1:8000/api/physical/{}/'.format(id), data = {'height':height, 'weight':weight, 'date':date, 'user':user.id})
            if r.status_code == 200 or 201:
                data = r.json()
                print(data)
                return redirect('physical_list')
        else:
            msg = 'Errors: %s' % form.errors.as_text()
            return HttpResponse(msg, status=400)

#CALL API DELETE
@csrf_exempt
def delete_physical(request, id):
    if utilities.is_permission_granted(request.user, 'delete_physicalmodel'):
        r = requests.delete('http://127.0.0.1:8000/api/physical/{}/'.format(id))

        if r.status_code == 200:
            messages.success(request, f'Delete successfully')
            data = r.json()
            print(data)

    return redirect('physical_list')

project/physical/templates/create_form.html
{% extends "base_project.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> <span class="page-title-icon bg-gradient-primary text-white mr-2">
      <i class="mdi mdi-google-physical-web"></i>
    </span> Physical </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active"><a href="{% url 'physical_list' %}">Physical</a></li>
            <li class="breadcrumb-item " aria-current="page">New Physical</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form class="forms-sample" action="/physical/create/" method="POST">
                {% csrf_token %}
                <div id="div_id_height" class="form-group row"> 
                    <label for="id_height" class=" requiredField col-sm-3 col-form-label">Height<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="number" name="height" min="0" max="200" value="" step="any" class="numberinput form-control" required id="id_height" placeholder="centimet"> </div>
                </div>
                <div id="div_id_weight" class="form-group row"> 
                    <label for="id_weight" class=" requiredField col-sm-3 col-form-label">Weight<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="number" name="weight" value="" step="any" class="numberinput form-control" required id="id_weight" placeholder="kilogram"> </div>
                </div>
                <div id="div_id_date" class="form-group row"> 
                    <label for="id_date" class=" requiredField col-sm-3 col-form-label">Date<span class="asteriskField">*</span> </label>
                    <div class="col-sm-9"> 
                        <input type="date" name="date" value="" class="datetimeinput form-control" required id="id_date">
                        <input type="hidden" name="initial-date" value="" id="initial-id_date"> 
                    </div>
                </div>
                <div style="display: none;" id="div_id_user" class="form-group"> 
                    <label for="id_user" class=" requiredField">User<span class="asteriskField">*</span> </label> 
                    <div class=""> 
                        <select name="user" class="select form-control" required id="id_user" value={{user}}> 
                            <option value="{{user.id}}" selected>{{user}}</option> 
                        </select>
                    </div>
                </div>
                <div class="row" style="justify-content: center">
                    <button type="submit" class="btn btn-inverse-success btn-fw col-md-4" style="margin: 0px 20px;">Save</button>
                    <a href="{% url 'physical_list' %}" class="btn btn-inverse-secondary btn-fw col-md-4" style="margin: 0px 20px;">Cancel</a>
                    <!-- <button class="btn btn-inverse-secondary btn-fw col-md-4" style="margin: 0px 20px;">Cancel</button> -->
                </div>
                <!-- <button type="submit" class="btn btn-inverse-success btn-fw col-md-6">Save</button>
                <button class="btn btn-inverse-secondary btn-fw col-md-6">Cancel</button> -->
            </form>
        </div>
    </div>
</div>
{% endblock content %}

project/physical/templates/detail_physical.html
{% extends "base_project.html" %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> <span class="page-title-icon bg-gradient-primary text-white mr-2">
      <i class="mdi mdi-google-physical-web"></i>
    </span> Physical </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active"><a href="{% url 'physical_list' %}">Physical</a></li>
            <li class="breadcrumb-item " aria-current="page">Physical List</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form action="{% url 'physical_update' id=physical.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div id="div_id_height" class="form-group row">
                    <label for="id_height" class=" requiredField col-sm-3 col-form-label">Height<span
                            class="asteriskField">*</span> </label>
                    <div class="col-sm-9">
                        <input type="number" value="{{physical.height}}" name="height" min="0" max="200" value=""
                            step="any" class="numberinput form-control" required id="id_height" placeholder="centimet">
                    </div>
                </div>
                <div id="div_id_weight" class="form-group row">
                    <label for="id_weight" class=" requiredField col-sm-3 col-form-label">Weight<span
                            class="asteriskField">*</span> </label>
                    <div class="col-sm-9">
                        <input type="number" value="{{physical.weight}}" name="weight" value="" step="any"
                            class="numberinput form-control" required id="id_weight" placeholder="kilogram"> </div>
                </div>
                <div id="div_id_date" class="form-group row">
                    <label for="id_date" class=" requiredField col-sm-3 col-form-label">Date<span
                            class="asteriskField">*</span> </label>
                    <div class="col-sm-9">
                        <input type="date" name="date" value="{{physical.date}}" class="datetimeinput form-control"
                            required id="id_date">
                        <input type="hidden" name="initial-date" value="" id="initial-id_date">
                    </div>
                </div>
                <div style="display: none;" id="div_id_user" class="form-group"> 
                    <label for="id_user" class=" requiredField">User<span class="asteriskField">*</span> </label> 
                    <div class=""> 
                        <select name="user" class="select form-control" required id="id_user" value={{user}}> 
                            <option value="{{user.id}}" selected>{{user}}</option> 
                        </select>
                    </div>
                </div>
                <!-- 
{{ abc }}
{{ abc.height.label }}
{{ abc.height }} -->
                <div class="row" style="justify-content: center">
                    <button type="submit" class="btn btn-inverse-warning btn-fw col-md-4"
                        style="margin: 0px 20px;">Update</button>
                    <a href="{% url 'physical_list' %}" class="btn btn-inverse-secondary btn-fw col-md-4"
                        style="margin: 0px 20px;">Cancel</a>
                    <!-- <button class="btn btn-inverse-secondary btn-fw col-md-4" style="margin: 0px 20px;">Cancel</button> -->
                </div>

                <!-- <button type="submit" class="btn btn-inverse-warning btn-fw col-md-12">Update</button> -->
            </form>
        </div>

    </div>
</div>
</div>
{% endblock content %}

project/physical/templates/list_physical.html
{% extends "base_project.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block search_form %}
<div class="search-field d-none d-md-block">
  <form class="d-flex align-items-center h-100" action="{% url 'physical_filter' %}" >
    {% csrf_token %}
    <div class="input-group" id="height">
      <div class="input-group-prepend bg-transparent">
        <i class="input-group-text border-0 mdi mdi-magnify"></i>
      </div>
      <input type="text" class="form-control bg-transparent border-0" id="height" name="height" placeholder="Search height">
    </div>
  </form>
</div>
{% endblock search_form %}
{% block page-header %}
<div class="page-header">
    <h3 class="page-title"> <span class="page-title-icon bg-gradient-primary text-white mr-2">
      <i class="mdi mdi-google-physical-web"></i>
    </span> Physical </h3>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active"><a href="{% url 'physical_list' %}">Physical</a></li>
            <li class="breadcrumb-item " aria-current="page">Physical List</li>
        </ol>
    </nav>
</div>
{% endblock page-header %}
{% block content %}
<!-- {% if messages %}
      {% for message in messages  %}
        <div style="color: blue;" class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
      {% endfor %}
    {% endif %} -->
    <a href="{% url 'create_physical' %}" class="btn btn-inverse-success btn-fw {% if not 'add_physicalmodel' in permissions %} d-none {% endif %}" style="margin-right: 20px; float: right; margin-bottom: 10px;">New physical</a>
    <!-- <button type="button" class="btn btn-inverse-success btn-fw">New physical</button> -->
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <table class="table table-striped ">
          <thead>
            <tr>
              <th> Date </th>
              <th> Height (cm) </th>
              <th> Weight (kg) </th>
            </tr>
          </thead>
          <tbody>
                {% for phy in physical.results  %}
                <tr>
                    <td> {{ phy.date }} </td>
                    <td> {{ phy.height }} </td>
                    <td>   {{ phy.weight }} </td>
                    <td class="{% if not 'change_physicalmodel' in permissions %} d-none {% endif %}">
                      <a class="btn btn-inverse-warning btn-fw" href="{% url 'physical_detail' id=phy.id %}">Update</a>
                    </td>
                    <td class="{% if not 'delete_physicalmodel' in permissions %} d-none {% endif %}">
                      <button type="button" class="btn btn-inverse-danger btn-fw" data-toggle="modal" data-target="#exampleModalCenter">
                        Delete
                      </button>
                      
                      <!-- Modal -->
                      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <!-- <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5> -->
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              Are you sure delete the physical created on {{phy.date}} ?
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-inverse-secondary btn-fw col-md-4" data-dismiss="modal">Cancle</button>
                              <a class="btn btn-inverse-danger btn-fw " href="{% url 'physical_delete' id=phy.id %}" >Delete</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </td>
                    <!-- <td> <a class="btn btn-inverse-danger btn-fw confirmation" href="{% url 'physical_delete' id=phy.id %}" onclick="return confirm('Are you sure?')">Delete</a></td> -->
                </tr>
                {% endfor %}
            
          </tbody>
        </table>
      </div>
    </div>
  </div>

{% endblock content %}